sudo: false

language: python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script:
  - flake8 .

script:
  - python -m unittest discover -s tests/
  - coverage run -m unittest discover -s tests/

after_success:
  - coveralls

deploy:
  provider: pypi
  user: chrisbrake
  password:
    secure: W5CHF7WkNX4HYnKeJXAIKRuEaybNfPx76S5WGCZfl92qLzAiJ/yDOIVHSLTa1mqPl9JOMWDCFaMMtAFPVtEbTw8NUBQbMJgRTwGmTGW3+fWuyW+fdJIR/HUcP2GnJ43jm9xloxlIfeVxanMYjBOuOcHBuANwlfMvm5/pVjw5jbsK1xIFqKL+BWw1NwpUhQhV0M8MKZtrfYUZSE5AdgWkrnaotrpp8cDVKUiC2ejRleMRWDB2oCCVCMU0bIcB+VLdi2OIQJXvWV+KcsbZzZO3A2/GdcgMZgrBE4QxZ5mtFqqReUHj6lr+LkhvD5zutlN5df7vvn2SV0UbbLmtXt1Evqhrosbic9Q4UPs/AX5WIyYA9DEO75EI6EbYNnxkwgb85w+cL0eYUN6IO3tn1luFzjz9M7SDPilQkXPGloUAXafavm9F5rwTMAnR1KOImZIkngn+3sdDvxjTKhwCNUklKx/74R8m/qKQ6EYbRDKgzbaBnlOx3R/72jizYVLcMAo42s8DjwZaihvSwaf92JUir6INBrIh7yCcG/o+kQ5+Z+SGnt0Q5XC/KqaVD2ByA85OEB52dc6cTedBydAkMq/bnePLTRu+sWxKVMQEbbG7HF42DdhbymjIq/x5HALAeYdGZLostWb9qqvJxI7le3iwOus/+lkwtZh/gTyp2rnV5dg=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
