sudo: false

language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script:
  - flake8 .

script:
  - python -m unittest discover -s tests/
  - coverage run -m unittest discover -s tests/

after_success:
  - coveralls
